#!/usr/bin/env python3
"""
WBGT Calculator (ABM and Liljegren Models) - Version 2
------------------------------------------------------
This script provides a highly accurate, physically-based implementation of the
Liljegren (2008) Wet Bulb Globe Temperature (WBGT) model, compared against the
simplified Australian Bureau of Meteorology (ABM) model.

It has been enhanced to process full 5-day / 3-hour (40 forecast periods) 
OpenWeatherMap JSON forecast files, with an automated clear-sky solar 
radiation estimator that dynamically scales based on cloud cover percentage.

Author: Generated by Gemini Notebook
Version: 2.0
Date: 2026-08-23
"""

import math
import json
import sys
import os
import argparse
from datetime import datetime

class WBGTCalculator:
    def __init__(self, lat=33.95, lon=-83.37):
        """
        Initialize the calculator with geographic coordinates.
        Default is set to Athens, Georgia (USA).
        """
        self.lat = lat
        self.lon = lon
        
        # Physical and empirical constants
        self.SIGMA = 5.670374419e-8  # Stefan-Boltzmann constant (W/m2 K4)
        self.EPSILON_G = 0.95        # Globe emissivity
        self.ALPHA_G = 0.05          # Ground albedo
        self.ALPHA_SFC = 0.45        # Surface albedo of the black globe
        self.D_GLOBE = 0.0508        # Standard 2-inch globe diameter (meters)
        
        # Wetted wick parameters
        self.D_WICK = 0.004          # Wick diameter (meters)
        self.EPSILON_W = 0.95        # Wick emissivity
        
        # Meteorological constants
        self.NU = 1.5e-5             # Kinematic viscosity of air (m2/s)
        self.K_AIR = 0.026           # Thermal conductivity of air (W/m K)
        self.PR = 0.709              # Prandtl number
        self.SC = 0.614              # Schmidt number
        self.M_RATIO = 18.015 / 28.97 # Ratio of molecular weights (H2O/Air)
        self.PR_SC_RATIO = (self.PR / self.SC) ** 0.56
        self.CP = 1005.0             # Specific heat of air (J/kg K)

    def get_solar_zenith_angle(self, dt_txt):
        """
        Calculate solar zenith angle in radians from UTC timestamp.
        """
        try:
            dt = datetime.strptime(dt_txt, "%Y-%m-%d %H:%M:%S")
        except ValueError:
            dt = datetime.fromisoformat(dt_txt.replace("Z", "+00:00"))
            
        lat_rad = math.radians(self.lat)
        day_of_year = dt.timetuple().tm_yday
        
        # Fractional year in radians
        gamma = 2.0 * math.pi / 365.0 * (day_of_year - 1 + (dt.hour - 12) / 24.0)
        
        # Equation of time in minutes
        eqt = 229.18 * (0.000075 + 0.001868 * math.cos(gamma) - 0.032077 * math.sin(gamma)
                        - 0.014615 * math.cos(2.0 * gamma) - 0.040849 * math.sin(2.0 * gamma))
        
        # Solar declination angle in radians
        decl = 0.006918 - 0.399912 * math.cos(gamma) + 0.070257 * math.sin(gamma) \
               - 0.006758 * math.cos(2.0 * gamma) + 0.00907 * math.sin(2.0 * gamma) \
               - 0.002697 * math.cos(3.0 * gamma) + 0.00148 * math.sin(3.0 * gamma)
               
        # Time offset in minutes
        time_offset = eqt + 4.0 * self.lon
        
        # True solar time in minutes
        tst = dt.hour * 60.0 + dt.minute + dt.second / 60.0 + time_offset
        
        # Solar hour angle in degrees
        ha = (tst / 4.0) - 180.0
        ha_rad = math.radians(ha)
        
        # Cosine of zenith angle
        cos_zenith = math.sin(lat_rad) * math.sin(decl) + math.cos(lat_rad) * math.cos(decl) * math.cos(ha_rad)
        cos_zenith = max(-1.0, min(1.0, cos_zenith))
        
        return math.acos(cos_zenith)

    def estimate_solar_radiation(self, dt_txt, cloud_percent):
        """
        Estimate solar radiation (W/m2) using solar zenith angle and cloud cover.
        Uses a standard clear-sky model scaled down by cloud cover.
        """
        zenith_rad = self.get_solar_zenith_angle(dt_txt)
        cos_z = math.cos(zenith_rad)
        
        # If the sun is below the horizon, solar radiation is 0
        if cos_z <= 0:
            return 0.0
            
        # Standard clear-sky global horizontal irradiance (GHI) model:
        # I_clear = I_solar_constant * cos(zenith) * atmospheric_transmissivity
        # Using a typical transmissivity of 0.75 for clear conditions
        solar_constant = 1367.0
        ghi_clear = solar_constant * cos_z * 0.75
        
        # Kasten-Czeplak cloud cover adjustment formula:
        # GHI = GHI_clear * (1 - A * (cloud_fraction ** B))
        # Where typical empirical values are A = 0.75 and B = 2.0
        cloud_fraction = cloud_percent / 100.0
        ghi_estimated = ghi_clear * (1.0 - 0.75 * (cloud_fraction ** 2))
        
        return max(0.0, ghi_estimated)

    def calculate_vapor_pressure(self, dew_point_c):
        """
        Calculate actual vapor pressure in hPa from dew point temperature.
        Uses the Magnus-Tetens formula.
        """
        return 6.112 * math.exp(17.67 * dew_point_c / (dew_point_c + 243.5))

    def calculate_abm_wbgt(self, temp_c, dew_point_c):
        """
        Calculate simplified WBGT using the Australian Bureau of Meteorology (ABM) model.
        """
        e = self.calculate_vapor_pressure(dew_point_c)
        return 0.567 * temp_c + 0.393 * e + 3.94

    def solve_liljegren_model(self, temp_c, dew_point_c, wind_speed_mps, pressure_hPa, solar_radiation_w_m2, dt_txt):
        """
        Iteratively solve the full energy-balance equations for natural wet bulb
        temperature (Tw) and globe temperature (Tg) under the Liljegren (2008) model.
        """
        # Actual vapor pressure of air
        e_a = self.calculate_vapor_pressure(dew_point_c)
        
        # Solar zenith angle
        zenith_rad = self.get_solar_zenith_angle(dt_txt)
        cos_z = max(0.01, math.cos(zenith_rad))
        
        Ta_K = temp_c + 273.15
        
        # 1. Direct radiation fraction f_dir based on clearness index
        S_0 = 1367.0 # Solar constant (W/m2)
        K_t = solar_radiation_w_m2 / (S_0 * cos_z)
        K_t = max(0.0, min(1.0, K_t))
        
        if K_t <= 0.22:
            f_dif = 1.0
        elif K_t <= 0.80:
            f_dif = 1.0 - 0.9 * (K_t - 0.22)
        else:
            f_dif = 0.15
        f_dir = 1.0 - f_dif
        
        # 2. Convective heat transfer coefficient h_g for Globe (sphere)
        # Limit wind speed to a minimum of 0.13 m/s to account for natural convection
        wind_speed_eff = max(wind_speed_mps, 0.13)
        Re_g = (wind_speed_eff * self.D_GLOBE) / self.NU
        Nu_g = 2.0 + 0.6 * (Re_g ** 0.5) * (self.PR ** (1/3))
        h_g = Nu_g * self.K_AIR / self.D_GLOBE
        
        # 3. Air emissivity
        eps_a = 1.24 * (e_a / Ta_K) ** (1/7)
        
        # 4. Solar term for Globe
        brackets = (0.5 / cos_z) * f_dir + self.ALPHA_SFC
        term3_solar = (solar_radiation_w_m2 / (2.0 * self.EPSILON_G * self.SIGMA)) * (1.0 - self.ALPHA_G) * brackets
        
        # Solve for Globe Temperature (Tg) using Newton-Raphson
        Tg_K = Ta_K
        for _ in range(100):
            F = Tg_K**4 - 0.5 * (1.0 + eps_a) * (Ta_K**4) + (h_g / (self.EPSILON_G * self.SIGMA)) * (Tg_K - Ta_K) - term3_solar
            dF = 4.0 * (Tg_K**3) + (h_g / (self.EPSILON_G * self.SIGMA))
            dTg = F / dF
            Tg_K -= dTg
            if abs(dTg) < 1e-5:
                break
                
        Tg_c = Tg_K - 273.15
        
        # 5. Calculate Mean Radiant Temperature (T_mrt)
        T_mrt_K = (Tg_K**4 + (h_g / (self.EPSILON_G * self.SIGMA)) * (Tg_K - Ta_K)) ** 0.25
        
        # 6. Convective heat transfer coefficient h_w for Wick (cylinder)
        Re_w = (wind_speed_eff * self.D_WICK) / self.NU
        Nu_w = 0.281 * (Re_w ** 0.6) * (self.PR ** 0.33)
        h_w = Nu_w * self.K_AIR / self.D_WICK
        
        # 7. Solve for Wet Bulb Temperature (Tw) using Newton-Raphson
        Tw_c = (temp_c + dew_point_c) / 2.0
        for _ in range(100):
            # Vapor pressure of wick at current Tw
            e_w = 6.112 * math.exp(17.67 * Tw_c / (Tw_c + 243.5))
            
            # Latent heat of vaporization of water
            DeltaH = (2.501 - 0.00237 * Tw_c) * 1e6
            
            # Convective mass transfer / cooling (Term 2)
            term2_conv = (DeltaH / self.CP) * self.M_RATIO * self.PR_SC_RATIO * ((e_w - e_a) / (pressure_hPa - e_w))
            
            # Radiation exchange (Term 3)
            Tw_K = Tw_c + 273.15
            term3_rad = (self.EPSILON_W * self.SIGMA / h_w) * (T_mrt_K**4 - Tw_K**4)
            
            # Energy balance target
            F_tw = Tw_c - temp_c + term2_conv - term3_rad
            
            # Derivative of energy balance for Newton-Raphson
            d_ew = e_w * 4302.645 / ((Tw_c + 243.5) ** 2)
            d_term2 = (DeltaH / self.CP) * self.M_RATIO * self.PR_SC_RATIO * (d_ew * (pressure_hPa - e_w) + (e_w - e_a) * d_ew) / ((pressure_hPa - e_w) ** 2)
            d_term3 = -4.0 * (self.EPSILON_W * self.SIGMA / h_w) * (Tw_K ** 3)
            
            dF_tw = 1.0 + d_term2 - d_term3
            
            dTw = F_tw / dF_tw
            Tw_c -= dTw
            if abs(dTw) < 1e-5:
                break
                
        # 8. Final Liljegren WBGT
        wbgt_liljegren = 0.7 * Tw_c + 0.2 * Tg_c + 0.1 * temp_c
        
        return {
            "Tw_c": Tw_c,
            "Tg_c": Tg_c,
            "wbgt_liljegren": wbgt_liljegren,
            "solar_zenith_deg": math.degrees(zenith_rad)
        }


    def process_observation(self, obs, solar_radiation=None, lat=None, lon=None):
        """Process one OpenWeather forecast record using supplied solar radiation."""
        if lat is not None:
            self.lat = lat
        if lon is not None:
            self.lon = lon

        temp = obs["main"]["temp"]
        dew_point = obs["main"]["dew_point"]
        wind_speed = obs["wind"]["speed"]
        pressure = obs["main"]["pressure"]
        humidity = obs["main"].get("humidity")
        visibility = obs.get("visibility")
        dt_txt = obs["dt_txt"]
        cloud_percent = obs.get("clouds", {}).get("all", 0)

        if solar_radiation is None:
            raise ValueError("Solar radiation is required. Supply it from the Open-Meteo JSON.")

        wbgt_abm = self.calculate_abm_wbgt(temp, dew_point)
        liljegren = self.solve_liljegren_model(
            temp_c=temp,
            dew_point_c=dew_point,
            wind_speed_mps=wind_speed,
            pressure_hPa=pressure,
            solar_radiation_w_m2=solar_radiation,
            dt_txt=dt_txt,
        )

        return {
            "timestamp": dt_txt,
            "location": {"lat": self.lat, "lon": self.lon},
            "inputs": {
                "air_temp_c": temp,
                "dew_point_c": dew_point,
                "wind_speed_mps": wind_speed,
                "pressure_hPa": pressure,
                "humidity": humidity,
                "visibility_m": visibility,
                "clouds_percent": cloud_percent,
                "solar_rad_w_m2": solar_radiation,
            },
            "abm_model": {"wbgt_c": wbgt_abm},
            "liljegren_model": {
                "wet_bulb_c": liljegren["Tw_c"],
                "globe_temp_c": liljegren["Tg_c"],
                "wbgt_c": liljegren["wbgt_liljegren"],
                "solar_zenith_deg": liljegren["solar_zenith_deg"],
            },
            "difference_c": wbgt_abm - liljegren["wbgt_liljegren"],
        }


def get_risk_category(wbgt_val):
    if wbgt_val < 22.3:
        return "Low Risk", "Normal Activity (Ensure general hydration)"
    elif wbgt_val < 25.7:
        return "Moderate Risk", "Normal Activity (Monitor fluid intake & rest cycles)"
    elif wbgt_val < 27.9:
        return "High Risk", "Normal Activity (Frequent water breaks required)"
    elif wbgt_val < 30.1:
        return "Very High Risk", "Discretion in planning intense/prolonged exercise"
    elif wbgt_val < 32.3:
        return "Extreme Risk", "Limit intense exercise and total heat exposure"
    return "Hazardous", "CANCEL ALL EXERCISE (Uncompensable Heat Stress)"


def load_openmeteo_radiation(path):
    """Return {YYYY-MM-DD HH:MM:SS: shortwave_radiation} from Open-Meteo JSON."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    hourly = data.get("hourly", {})
    times = hourly.get("time", [])
    radiation = hourly.get("shortwave_radiation", [])
    if not times or len(times) != len(radiation):
        raise ValueError("Open-Meteo JSON must contain matching hourly.time and hourly.shortwave_radiation arrays.")

    out = {}
    for t, r in zip(times, radiation):
        key = t.replace("T", " ")
        if len(key) == 16:
            key += ":00"
        out[key] = float(r) if r is not None else 0.0
    return out, data.get("latitude"), data.get("longitude")


def process_files(openweather_path, radiation_path, output_csv_path):
    """Read both JSON files, match timestamps, and calculate Liljegren WBGT."""
    with open(openweather_path, "r", encoding="utf-8") as f:
        weather = json.load(f)

    if "list" not in weather:
        raise ValueError("OpenWeather JSON must contain a 'list' array.")

    radiation_map, rad_lat, rad_lon = load_openmeteo_radiation(radiation_path)
    lat = weather.get("city", {}).get("coord", {}).get("lat", rad_lat)
    lon = weather.get("city", {}).get("coord", {}).get("lon", rad_lon)
    if lat is None or lon is None:
        raise ValueError("Latitude/longitude not found in the JSON files.")

    calc = WBGTCalculator(lat=lat, lon=lon)
    results = []
    missing = []

    for obs in weather["list"]:
        timestamp = obs["dt_txt"]
        if timestamp not in radiation_map:
            missing.append(timestamp)
            continue
        results.append(calc.process_observation(obs, solar_radiation=radiation_map[timestamp]))

    if missing:
        raise ValueError("No matching Open-Meteo radiation timestamp for: " + ", ".join(missing))

    fieldnames = [
        "Timestamp", "Air_Temp_C", "Relative_Humidity_Percent", "Dew_Point_C",
        "Pressure_hPa", "Wind_Speed_m_s", "Cloud_Cover_Percent",
        "Shortwave_Radiation_W_m2", "Solar_Zenith_Deg",
        "Liljegren_Wet_Bulb_C", "Liljegren_Globe_C", "Liljegren_WBGT_C",
        "ABM_WBGT_C", "Model_Discrepancy_C", "ACSM_Risk_Category", "Recommended_Action"
    ]

    with open(output_csv_path, "w", newline="", encoding="utf-8") as csvfile:
        import csv
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            wbgt = r["liljegren_model"]["wbgt_c"]
            risk, action = get_risk_category(wbgt)
            writer.writerow({
                "Timestamp": r["timestamp"],
                "Air_Temp_C": r["inputs"]["air_temp_c"],
                "Relative_Humidity_Percent": r["inputs"]["humidity"],
                "Dew_Point_C": r["inputs"]["dew_point_c"],
                "Pressure_hPa": r["inputs"]["pressure_hPa"],
                "Wind_Speed_m_s": r["inputs"]["wind_speed_mps"],
                "Cloud_Cover_Percent": r["inputs"]["clouds_percent"],
                "Shortwave_Radiation_W_m2": round(r["inputs"]["solar_rad_w_m2"], 2),
                "Solar_Zenith_Deg": round(r["liljegren_model"]["solar_zenith_deg"], 2),
                "Liljegren_Wet_Bulb_C": round(r["liljegren_model"]["wet_bulb_c"], 2),
                "Liljegren_Globe_C": round(r["liljegren_model"]["globe_temp_c"], 2),
                "Liljegren_WBGT_C": round(wbgt, 2),
                "ABM_WBGT_C": round(r["abm_model"]["wbgt_c"], 2),
                "Model_Discrepancy_C": round(r["difference_c"], 2),
                "ACSM_Risk_Category": risk,
                "Recommended_Action": action,
            })

    print(f"Processed {len(results)} forecast records.")
    print(f"Latitude: {lat}, Longitude: {lon}")
    print(f"Output: {output_csv_path}")
    print("\nFirst 10 WBGT results:")
    for r in results[:10]:
        print(f"{r['timestamp']} | Ta={r['inputs']['air_temp_c']:.1f} C | "
              f"RH={r['inputs']['humidity']}% | SW={r['inputs']['solar_rad_w_m2']:.1f} W/m2 | "
              f"WBGT={r['liljegren_model']['wbgt_c']:.2f} C")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calculate Liljegren WBGT directly from OpenWeather + Open-Meteo JSON files.")
    parser.add_argument("--weather", required=True, help="OpenWeather 5-day/3-hour JSON file")
    parser.add_argument("--radiation", required=True, help="Open-Meteo hourly radiation JSON file")
    parser.add_argument("--out-csv", default="wbgt_forecast_report.csv", help="Output CSV")
    args = parser.parse_args()

    process_files(args.weather, args.radiation, args.out_csv)